### ISSUE TITLE
Blackmagic Audio Monitor

### ISSUE THREAD

**Issue by edinc90** [bitfocus/companion-module-bmd-audiomonitor#1]
https://resource.holdan.co.uk/Blackmagic%20Design/manuals/Blackmagic_Design_Audio_Monitor.pdf

Page 16-18 details the commands for controlling this device. It works with the generic TCP-UDP module, but requires 3 commands per button push, due to needing new lines at the end of each part of the commands.

E.g.:
AUDIO INPUT: \n
Routing: Speaker Stereo SDI Stereo 1-2 \n
\n

**Comment by edinc90** [comment]
I'm testing it now. It seems when toggling from Analog to SDI audio, the last selected SDI audio pair is activated, not the intended one. For example: SDI 15-16 is active, then I select XLR, then I select SDI 1-2. But instead of SDI 1-2, I get SDI 15-16. Pushing the button for SDI 1-2 again activates SDI 1-2.

All the other functions seem to work well though.

**Comment by daniep01** [comment]
Thanks for testing. I wonder if there's a problem in the blackmagic software because the commands I send are extremely simple and there is only one way to switch the input. Can you check you are using the latest BM audiomonitor firmware?

**Comment by edinc90** [comment]
This looks like it is a glitch in the Blackmagic firmware. I've confirmed the same behavior when directly connected to the audio monitor via Putty, I am running the latest firmware, version 3.0.3.

**Comment by daniep01** [comment]
Hi,

Thanks for checking. You could try raising support ticket with Blackmagic to make them aware. In the meantime I suggest putting the switch input action twice on one button, maybe with a delay in between.
